# Generated by Django 3.1.3 on 2021-01-28 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='posts.comment')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_notification', to='posts.notificationdetails')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='posts.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='commentnotification',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notification', to='posts.notificationdetails'),
        ),
    ]
