# Generated by Django 3.1.1 on 2020-10-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201028_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profile',
            new_name='author',
        ),
    ]
