# Generated by Django 3.1.1 on 2020-11-02 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20201030_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
