# Generated by Django 3.1.1 on 2020-11-02 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postlike_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
