# Generated by Django 3.1.1 on 2020-11-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_commentlike_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
