# Generated by Django 3.1.1 on 2020-11-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20201104_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='postlike',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
