# Generated by Django 3.1.1 on 2020-11-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20201109_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-likes']},
        ),
    ]
