# Generated by Django 3.1.1 on 2020-11-10 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201109_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created', '-likes']},
        ),
    ]
