# Generated by Django 3.1.1 on 2020-11-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20201109_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-likes', '-created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created', '-likes']},
        ),
    ]
