# Generated by Django 3.1.3 on 2020-12-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20201215_1511'),
        ('posts', '0021_auto_20201109_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='comment',
            name='layer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_profiles',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(related_name='post_views', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('posts', models.ManyToManyField(related_name='hashtags', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment_relationship', to='posts.comment')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_relationship', to='posts.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='_comment_comments_+', through='posts.CommentRelationship', to='posts.Comment'),
        ),
    ]
