# Generated by Django 3.1.3 on 2020-12-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20201228_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentrelationship',
            name='base_comment',
        ),
        migrations.RemoveField(
            model_name='commentrelationship',
            name='comment',
        ),
    ]
