# Generated by Django 3.1.3 on 2020-12-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20201228_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrelationship',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_relationship', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='commentrelationship',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment_relationship', to='posts.comment'),
        ),
    ]
