# Generated by Django 3.1.3 on 2020-12-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20201228_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_profiles',
        ),
    ]
