# Generated by Django 3.1.3 on 2020-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20201130_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('posts', models.ManyToManyField(related_name='hashtags', to='posts.Post')),
            ],
        ),
    ]
