# Generated by Django 3.1.3 on 2020-12-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20201204_2301'),
        ('posts', '0026_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(related_name='post_views', to='profiles.Profile'),
        ),
    ]
