# Generated by Django 3.1.3 on 2021-01-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notifications_number',
            field=models.IntegerField(default=0),
        ),
    ]
