# Generated by Django 3.1.3 on 2021-01-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_notification_notifications_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['-created']},
        ),
    ]
