# Generated by Django 3.1.3 on 2020-12-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20201215_1511'),
        ('posts', '0027_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_profiles',
            field=models.ManyToManyField(related_name='tagged_posts', to='profiles.Profile'),
        ),
    ]
