# Generated by Django 3.1.3 on 2020-12-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20201215_1511'),
        ('posts', '0028_post_tagged_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tagged_profiles',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='profiles.Profile'),
        ),
    ]
