# Generated by Django 3.1.3 on 2020-12-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20201222_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='layer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='CommentRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_comment', to='posts.comment')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='_comment_comments_+', through='posts.CommentRelationship', to='posts.Comment'),
        ),
    ]
