# Generated by Django 3.1.3 on 2021-01-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='posts.Interest'),
        ),
    ]
