# Generated by Django 3.1.3 on 2021-01-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20210110_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Interest'),
        ),
    ]
