# Generated by Django 3.1.3 on 2021-01-14 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0031_auto_20210111_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_profiles',
            field=models.ManyToManyField(blank=True, related_name='my_mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
