# Generated by Django 3.1.3 on 2021-01-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_post_tagged_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_profiles',
        ),
    ]
