# Generated by Django 3.1.3 on 2021-01-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_post_tagged_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=50000),
        ),
    ]
