# Generated by Django 3.1.3 on 2021-01-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20210116_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interest',
            new_name='PostInterest',
        ),
    ]
