# Generated by Django 3.1.3 on 2021-02-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210126_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weights',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.weights'),
        ),
    ]
