# Generated by Django 3.1.1 on 2020-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201026_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
