# Generated by Django 3.1.1 on 2020-11-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_interest_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
