# Generated by Django 3.1.1 on 2020-11-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20201106_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to='media/'),
        ),
    ]
