# Generated by Django 3.1.1 on 2020-11-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20201107_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['title']},
        ),
    ]
