# Generated by Django 3.1.1 on 2020-11-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
