# Generated by Django 3.1.3 on 2020-12-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20201130_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_avatar.jpg', upload_to='profile/'),
        ),
    ]
