# Generated by Django 3.1.3 on 2020-12-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20201215_1511'),
    ]

    operations = [
        
    ]
