# Generated by Django 3.1.3 on 2020-12-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20201230_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weights',
            old_name='post_weights',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='weights',
            old_name='profile_weights',
            new_name='profile',
        ),
    ]
