# Generated by Django 3.1.3 on 2020-12-30 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20201230_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weights',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.postweights'),
        ),
        migrations.AlterField(
            model_name='weights',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profileweights'),
        ),
    ]
