# Generated by Django 3.1.3 on 2020-12-30 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20201230_1809'),
    ]

    operations = [
        
    ]
