# Generated by Django 3.1.3 on 2020-12-30 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20201230_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weights',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.postweights'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weights',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profileweights'),
        ),
    ]
