# Generated by Django 3.1.3 on 2020-12-31 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20201230_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_weight', models.FloatField()),
                ('age_weight', models.FloatField()),
                ('friends_weight', models.FloatField()),
                ('is_friend_weight', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='postweights',
            old_name='age_weight',
            new_name='author_weight',
        ),
        migrations.RenameField(
            model_name='postweights',
            old_name='friends_weight',
            new_name='date_weight',
        ),
        migrations.RenameField(
            model_name='postweights',
            old_name='interest_weight',
            new_name='likes_weight',
        ),
        migrations.RemoveField(
            model_name='postweights',
            name='is_friend_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_weights',
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.postweights')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profileweights')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='weights',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.weights'),
        ),
    ]
