"""
Django settings for napker project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

STATE = 'production'

if STATE == 'production':
    from .settings_prod import *
elif STATE == 'development':
    from .settings_dev import *

ALLOWED_HOSTS = ['napker.herokuapp.com']
