# Generated by Django 3.1.1 on 2020-10-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='viewed',
            new_name='read',
        ),
    ]
