# Generated by Django 3.1.3 on 2020-12-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_feedback_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(-1, -1), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
