export default {
    emoji: 'emoji',
    emojiSuggestions: 'emojiSuggestions',
    emojiSuggestionsEntry: 'emojiSuggestionsEntry',
    emojiSuggestionsEntryFocused: 'emojiSuggestionsEntryFocused',
    emojiSuggestionsEntryText: 'emojiSuggestionsEntryText',
    emojiSuggestionsEntryIcon: 'emojiSuggestionsEntryIcon',
    emojiSelect: 'emojiSelect',
    emojiSelectButton: 'emojiSelectButton',
    emojiSelectButtonPressed: 'emojiSelectButtonPressed',
    emojiSelectPopover: 'emojiSelectPopover blur',
    emojiSelectPopoverClosed: 'emojiSelectPopoverClosed',
    emojiSelectPopoverTitle: 'emojiSelectPopoverTitle',
    emojiSelectPopoverGroups: 'emojiSelectPopoverGroups',
    emojiSelectPopoverGroup: 'emojiSelectPopoverGroup',
    emojiSelectPopoverGroupTitle: 'emojiSelectPopoverGroupTitle',
    emojiSelectPopoverGroupList: 'emojiSelectPopoverGroupList',
    emojiSelectPopoverGroupItem: 'emojiSelectPopoverGroupItem',
    emojiSelectPopoverToneSelect: 'emojiSelectPopoverToneSelect',
    emojiSelectPopoverToneSelectList: 'emojiSelectPopoverToneSelectList',
    emojiSelectPopoverToneSelectItem: 'emojiSelectPopoverToneSelectItem',
    emojiSelectPopoverEntry: 'emojiSelectPopoverEntry',
    emojiSelectPopoverEntryFocused: 'emojiSelectPopoverEntryFocused',
    emojiSelectPopoverEntryIcon: 'emojiSelectPopoverEntryIcon',
    emojiSelectPopoverNav: 'emojiSelectPopoverNav',
    emojiSelectPopoverNavItem: 'emojiSelectPopoverNavItem',
    emojiSelectPopoverNavEntry: 'emojiSelectPopoverNavEntry',
    emojiSelectPopoverNavEntryActive: 'emojiSelectPopoverNavEntryActive',
    emojiSelectPopoverScrollbarOuter: 'emojiSelectPopoverScrollbarOuter',
    emojiSelectPopoverScrollbar: 'emojiSelectPopoverScrollbar',
    emojiSelectPopoverScrollbarThumb: 'emojiSelectPopoverScrollbarThumb'
}